### ISSUE TITLE
Copy ID of patch or series only

### ISSUE THREAD

**Issue by Qeole** [Qeole/seams#2]
[Some users](https://addons.thunderbird.net/en-GB/thunderbird/addon/seams/reviews/1166347/) would appreciate an easy way to copy just the ids for patches and series (not the whole command line to check them out). This is probably not a common use case and could be gated by a configuration option.

**Comment by matttbe** [comment]
Hi @Qeole 

Thank you for having created this ticket!

On my side, I did this simple "workaround":

```diff
diff --git a/popup/popup.html b/popup/popup.html
index 30e0803..5a78d93 100644
--- a/popup/popup.html
+++ b/popup/popup.html
@@ -120,11 +120,13 @@
           <div class="title">Apply Locally <span class="help-note">(Click commands to copy to clipboard)</span></div>
           <div class="subtitle">Patch</div>
           <ul class="copy-list">
+              <li><code><span id="popup-apply-patch-pw"></span></code></li>
               <li><code>git-pw patch apply <span id="popup-apply-patch-pw"></span></code></li>
               <li><code>curl <span id="popup-apply-patch-git"></span> | git am -</code></li>
           </ul>
           <div class="subtitle series">Series</div>
           <ul class="copy-list series">
+              <li><code><span id="popup-apply-series-pw"></span></code></li>
               <li><code>git-pw series apply <span id="popup-apply-series-pw"></span></code></li>
               <li><code>curl <span id="popup-apply-series-git"></span> | git am -</code></li>
           </ul>
```

Just in case others needs this non common use case.

**Comment by Qeole** [comment]
Nice!

For your information I started to work on a page to set up preferences for the add-on, and once we have that we can use a list of checkboxes to pick optional fields to use in the pop-up. I pushed [the branch](https://github.com/Qeole/seams/tree/select_patchwork) for reference, but this is still very much in progress and not useable yet.

**Comment by Qeole** [comment]
Hi @matttbe, I've implemented the _Preferences_ page to configure the options for the Patchwork instance(s) to use, and to opt-in to display the ids of the patches and series. Do you have a chance to try the version on [my branch](https://github.com/Qeole/seams/tree/select_patchwork) to see if that allows you to retrieve what you want?

(It seems to work well for me (tested with kernel + DPDK Patchworks) and I'll probably merge it soon.)

**Comment by matttbe** [comment]
Hi @Qeole,

Great, thank you for this Preferences page!

I was able to add a new Patchwork instance with the same URL (kernel.org) and `@lists.linux.dev` and also to enable the option to copy the patches and series IDs. Everything work with both Netdev and MPTCP ML, thanks!

I didn't check the code but is there a priority? For some patches where we send patches to both MPTCP and Netdev ML, info from MPTCP project are displayed and for others, it is from Netdev. But the project that is picked is consistent for all patches of the same series :)
It is just to know if I can do something to influence which one is displayed in priority.

**Comment by Qeole** [comment]
> I was able to add a new Patchwork instance with the same URL (kernel.org) and `@lists.linux.dev` and also to enable the option to copy the patches and series IDs. Everything work with both Netdev and MPTCP ML, thanks!

Awesome, thanks a lot for testing!

> I didn't check the code but is there a priority? For some patches where we send patches to both MPTCP and Netdev ML, info from MPTCP project are displayed and for others, it is from Netdev. But the project that is picked is consistent for all patches of the same series :)
> It is just to know if I can do something to influence which one is displayed in priority.

Hmm this is strange, I _expected_ the order to be always the same, and to be determined by whichever Patchwork instance comes first on the preferences page. The instances are stored in an array in Thunderbird's storage. When the add-on attempts to find the relevant instance for a patch, it retrieves that array, and tries all instances [in a `for ... of ...` loop](https://github.com/Qeole/seams/blob/8fb806d5df336aa4310946adc16d7bbac5f6641b/scripts/patches.js#L19) until it finds one (and breaks out of the loop). I expected the iteration to always pick the entries in the same order, I'm pretty sure the order is deterministic. And I don't understand why it differs between series but stays the same for a given thread (the add-on doesn't know about threads and has no particular processing for patches from a same series) :thinking:.

Just to be sure, you're a 100% certain that the patches should be picked for both instances (they have the relevant patterns for the two Patchwork instances)? Any chance you could have re-ordered the instances on the Preferences page between observing the different selections?  If not, could you point me to some examples in ML archives when I can have a look at the emails/headers, please? I'll try to do more testing on my side as well.

**Comment by matttbe** [comment]
Thank you for your reply!

> Hmm this is strange, I expected the order to be always the same, and to be determined by whichever Patchwork instance comes first on the preferences page.

I think that in my case, it doesn't matter which project is first in Seams because they are pointing to the same patchwork instance. But later, the patchwork REST API will pick one project or the other but that doesn't depend on Seams, no?

But except if we want to limit the request to one project, I'm not sure how we could put an order :)

>  If not, could you point me to some examples in ML archives when I can have a look at the emails/headers, please? I'll try to do more testing on my side as well.

Just in case you want to try, you can download:
* https://patchwork.kernel.org/project/mptcp/patch/20210527235430.183465-2-mathew.j.martineau@linux.intel.com/
* https://patchwork.kernel.org/project/mptcp/patch/20210527233140.182728-2-mathew.j.martineau@linux.intel.com/

**Comment by Qeole** [comment]
Oh, I see, thanks! I had not understood that the Patchwork instance was the same.

So what happens is that we query Patchwork with the message ID, and it returns a list of corresponding projects for that patch. Seams always picks _the first result_. Apparently the projects are not always ordered the same, you can compare the answers [for your first link: project 405 then 399](https://patchwork.kernel.org/api/1.2/patches/?msgid=20210527235430.183465-2-mathew.j.martineau@linux.intel.com), versus [the second link (opposite order)](https://patchwork.kernel.org/api/1.2/patches/?msgid=20210527233140.182728-2-mathew.j.martineau@linux.intel.com).

As you said, we could filter the request on a given project, but it might prevent finding the patch if it is not in that project. But without filtering in the request itself, since we get several results with details on the projects associated to the patches, we can do something better, I think: We can pick the patch associated to the project for which _the mailing list address_ matches _the pattern we use for the Patchwork instance we are working with_. In that case, the first project defined in the Preferences page should apply, _if_ the mailing list pattern is distinct enough (e.g. would not work to dissociate several projects with mailing lists `@vger.kernel.org` if the pattern is just `@vger.kernel.org`, but would work if the pattern filled for the project was `netdev@vger.kernel.org`—in your case, `@vger.kernel.org` and `@lists.linux.dev` won't overlap so it's fine).

Not sure if my explanations make sense... Anyway [I gave it a try](https://github.com/Qeole/seams/blob/882c9572702fec60a64ca231ef60794728ac3b4f/scripts/requests.js#L24), could you please try the same branch again (I forced-push) and let me know if things improved?

**Comment by matttbe** [comment]
> So what happens is that we query Patchwork with the message ID, and it returns a list of corresponding projects for that patch. Seams always picks _the first result_. Apparently the projects are not always ordered the same, you can compare the answers [for your first link: project 405 then 399](https://patchwork.kernel.org/api/1.2/patches/?msgid=20210527235430.183465-2-mathew.j.martineau@linux.intel.com), versus [the second link (opposite order)](https://patchwork.kernel.org/api/1.2/patches/?msgid=20210527233140.182728-2-mathew.j.martineau@linux.intel.com).

I see, thank you for the link and explanation!

> As you said, we could filter the request on a given project, but it might prevent finding the patch if it is not in that project. But without filtering in the request itself, since we get several results with details on the projects associated to the patches, we can do something better, I think: We can pick the patch associated to the project for which _the mailing list address_ matches _the pattern we use for the Patchwork instance we are working with_. In that case, the first project defined in the Preferences page should apply, _if_ the mailing list pattern is distinct enough (e.g. would not work to dissociate several projects with mailing lists `@vger.kernel.org` if the pattern is just `@vger.kernel.org`, but would work if the pattern filled for the project was `netdev@vger.kernel.org`—in your case, `@vger.kernel.org` and `@lists.linux.dev` won't overlap so it's fine).

I just noticed this `list_email` key in the JSON, good idea!

> Not sure if my explanations make sense... Anyway [I gave it a try](https://github.com/Qeole/seams/blob/882c9572702fec60a64ca231ef60794728ac3b4f/scripts/requests.js#L24), could you please try the same branch again (I forced-push) and let me know if things improved?

Wow, that was quick, thank you! I didn't know kernel devs were able to enjoy that much JavaScript :-D

But I just tried it and indeed, it improved things! Thank you, that is more consistent.
Please note that I had to do a minor modification:

```diff
diff --git a/scripts/requests.js b/scripts/requests.js
index afe669f..852ac1f 100644
--- a/scripts/requests.js
+++ b/scripts/requests.js
@@ -27,7 +27,7 @@ export async function getPatchInfo(patchwork, msgId) {
     // the mailing list pattern for the Patchwork instance we are working with.
     if (data.length > 1) {
         for (let p of data) {
-            if (p.project.list_email.hasSubstring(patchwork.mailingListString)) {
+            if (p.project.list_email.indexOf(patchwork.mailingListString) !== -1) {
                 patch = p;
                 break;
             }
```

(that's a shame we cannot use something like `endsWidth()`)

**Comment by qmonnet** [comment]
Silly me, I copied the `hasSubstring()` from another file of the add-on, but I forgot I had defined it myself in that file. Thanks a lot for testing, and for the fix! I'll update the code and I'll merge it.

**Comment by Qeole** [comment]
Silly me, I copied the `hasSubstring()` from another file of the add-on, but I forgot I had defined it myself in that file. Thanks a lot for testing, and for the fix! I'll update the code and I'll merge it.

**Comment by Qeole** [comment]
Now merged, tagged, and available straight from https://addons.thunderbird.net!

As for the JavaScript, well, I'm still waiting for Thunderbird to support add-ons written in eBPF :wink:. In the meantime, there was not much of a choice if I wanted to integrate Patchwork to Thunderbird. And it [all started](https://addons.mozilla.org/en-GB/firefox/addon/enlight/) before I contributed to the kernel anyway.

Thanks again for the tests and feedback, much appreciated.

**Comment by matttbe** [comment]
> Now merged, tagged, and available straight from https://addons.thunderbird.net!

Thank you! Already updated, everything good so far!

> As for the JavaScript, well, I'm still waiting for Thunderbird to support add-ons written in eBPF wink. In the meantime, there was not much of a choice if I wanted to integrate Patchwork to Thunderbird. And it all started before I contributed to the kernel anyway.

We can have game with eBPF, why not Thunderbird add-ons??? :stuck_out_tongue: 
Thank you for having initiated this extension! And thank you for the link for enlight, nice one too :-)

> Thanks again for the tests and feedback, much appreciated.

That's the least I can do!
